#各个key的冒号后边必须跟一个空格
spring:
#数据源信息
  datasource:
    type : com.alibaba.druid.pool.DruidDataSource
    url : jdbc:mysql://localhost:3306/springbootshop?useSSL=true
    username : root
    password : root
    driver-class-name : com.mysql.jdbc.Driver
#配置druid连接池
    druid:
          initial-size : 2
          max-active : 10
#      min-idle:
#      max-wait:
#      pool-prepared-statements:
#      max-pool-prepared-statement-per-connection-size:
#      validation-query:
#      validation-query-timeout:
#      test-on-borrow:
#      test-on-return:
#      test-while-idle:
#      time-between-eviction-runs-millis:
#      min-evictable-idle-time-millis:
#      max-evictable-idle-time-millis:
          filter:
         # 配置StatFilter 
                 stat:
                      db-type : h2
                      log-slow-sql : true
                      slow-sql-millis : 2000
         # 配置WallFilter 
                 wall:
                      enabled : true
                      db-type : h2
                      delete-allow : false
                      drop-table-allow : false
  jpa:
  #hibernate显示sql语句
    show-sql : true 
    database-platform : org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto : none
      naming:
        physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect
#配置freemarker
  freemarker:
    request-context-attribute : request
    
#添加对jsp的支持
  mvc:
    view:
      prefix : /WEB-INF/views/
      suffix : .jsp
#图片存储位置
myproperties:
  imageroot : static/image
#是否启用redis
  isRedis : no
    